export type DataHubConnectorKind = 'file' | 'database' | 'api' | 'cloud' | 'manufacturing' | 'manual';

export type DataHubConnector = {
  key: string;
  name: string;
  category: 'Files' | 'Databases' | 'Cloud' | 'Manufacturing' | 'Manual';
  kind: DataHubConnectorKind;
  description: string;
  authMethods: string[];
  requiredFields: string[];
  examples: string[];
};

export type DataHubStep = {
  key: string;
  label: string;
  helper: string;
};

export const dataHubSteps: DataHubStep[] = [
  { key: 'source', label: 'Source', helper: 'Pick where data comes from' },
  { key: 'connect', label: 'Connect', helper: 'Enter only required details' },
  { key: 'preview', label: 'Preview', helper: 'Check rows before loading' },
  { key: 'transform', label: 'Transform', helper: 'Clean and shape columns' },
  { key: 'map', label: 'Map', helper: 'Align source fields to modules' },
  { key: 'validate', label: 'Validate', helper: 'Find errors and warnings' },
  { key: 'load', label: 'Load', helper: 'Create draft or schedule refresh' },
];

export const dataHubConnectors: DataHubConnector[] = [
  {
    key: 'excel',
    name: 'Excel workbook',
    category: 'Files',
    kind: 'file',
    description: 'Import workbook sheets, named tables, multi-sheet exports, and ERP Excel files.',
    authMethods: ['No authentication', 'Protected workbook password', 'Cloud file link'],
    requiredFields: ['File or link', 'Sheet/table selection'],
    examples: ['.xlsx', '.xlsm', 'Named table'],
  },
  {
    key: 'csv_tsv',
    name: 'CSV / TSV',
    category: 'Files',
    kind: 'file',
    description: 'Delimited files with delimiter, encoding, header, and bad-row handling.',
    authMethods: ['No authentication', 'Folder permission'],
    requiredFields: ['File or folder', 'Delimiter', 'Encoding'],
    examples: ['.csv', '.tsv', 'Pipe-delimited file'],
  },
  {
    key: 'json',
    name: 'JSON',
    category: 'Files',
    kind: 'file',
    description: 'Nested JSON documents with flattening, array expansion, and schema detection.',
    authMethods: ['No authentication', 'API key', 'Bearer token'],
    requiredFields: ['File or URL', 'Root path'],
    examples: ['REST export', 'Nested array', 'Event payload'],
  },
  {
    key: 'xml',
    name: 'XML',
    category: 'Files',
    kind: 'file',
    description: 'XML feeds and ERP document structures with XPath-style row detection.',
    authMethods: ['No authentication', 'Basic authentication'],
    requiredFields: ['File or URL', 'Row node'],
    examples: ['IDoc XML', 'Invoice XML', 'Supplier feed'],
  },
  {
    key: 'pdf_table',
    name: 'PDF table extraction',
    category: 'Files',
    kind: 'file',
    description: 'Extract rows from invoices, statements, inspection reports, and tabular PDFs.',
    authMethods: ['No authentication'],
    requiredFields: ['PDF file', 'Page range'],
    examples: ['Invoice table', 'Certificate table', 'Statement'],
  },
  {
    key: 'folder_import',
    name: 'Folder import',
    category: 'Files',
    kind: 'file',
    description: 'Combine many files from one local, network, or cloud folder into one dataset.',
    authMethods: ['Folder permission', 'Cloud link'],
    requiredFields: ['Folder path', 'File pattern'],
    examples: ['Daily exports folder', '*.csv', '*.xlsx'],
  },
  {
    key: 'sql_server',
    name: 'SQL Server',
    category: 'Databases',
    kind: 'database',
    description: 'Read-only SQL Server tables, views, or approved queries.',
    authMethods: ['SQL login', 'Windows authentication', 'Managed identity'],
    requiredFields: ['Server', 'Database', 'Authentication'],
    examples: ['dbo.InventoryBalance', 'MES history view'],
  },
  {
    key: 'postgresql',
    name: 'PostgreSQL',
    category: 'Databases',
    kind: 'database',
    description: 'PostgreSQL schemas, operational tables, analytics marts, and views.',
    authMethods: ['Database password', 'IAM token', 'Connection string'],
    requiredFields: ['Host', 'Port', 'Database'],
    examples: ['public.stock_ledger', 'reporting.fact_orders'],
  },
  {
    key: 'mysql',
    name: 'MySQL',
    category: 'Databases',
    kind: 'database',
    description: 'MySQL operational, shop-floor, and reporting tables.',
    authMethods: ['Database password', 'Connection string'],
    requiredFields: ['Host', 'Database', 'Username'],
    examples: ['wms_bins', 'production_orders'],
  },
  {
    key: 'oracle',
    name: 'Oracle',
    category: 'Databases',
    kind: 'database',
    description: 'Oracle ERP schemas, finance tables, inventory views, and operational extracts.',
    authMethods: ['Database password', 'Oracle wallet'],
    requiredFields: ['Host', 'Service name', 'Authentication'],
    examples: ['EBS inventory', 'S/OP view'],
  },
  {
    key: 'mongodb',
    name: 'MongoDB',
    category: 'Databases',
    kind: 'database',
    description: 'Document collections with flattening, sample inference, and field mapping.',
    authMethods: ['Connection string', 'SCRAM credentials'],
    requiredFields: ['Connection string', 'Database', 'Collection'],
    examples: ['sensor_events', 'service_logs'],
  },
  {
    key: 'sqlite',
    name: 'SQLite',
    category: 'Databases',
    kind: 'database',
    description: 'Embedded database files from edge tools, local machines, and export utilities.',
    authMethods: ['File permission'],
    requiredFields: ['Database file'],
    examples: ['edge_cache.db', 'machine_export.sqlite'],
  },
  {
    key: 'data_warehouse',
    name: 'Data warehouse',
    category: 'Databases',
    kind: 'database',
    description: 'Curated warehouse views and analytics datasets for enterprise reporting.',
    authMethods: ['OAuth', 'Key pair', 'IAM role'],
    requiredFields: ['Warehouse endpoint', 'Database', 'Schema'],
    examples: ['Snowflake', 'BigQuery', 'Redshift'],
  },
  {
    key: 'sharepoint',
    name: 'SharePoint',
    category: 'Cloud',
    kind: 'cloud',
    description: 'SharePoint lists, libraries, Excel files, and controlled document folders.',
    authMethods: ['Microsoft OAuth', 'Service principal'],
    requiredFields: ['Site URL', 'Library/List'],
    examples: ['Inventory list', 'Quality documents'],
  },
  {
    key: 'google_sheets',
    name: 'Google Sheets',
    category: 'Cloud',
    kind: 'cloud',
    description: 'Google Sheets ranges, tabs, and shared spreadsheets.',
    authMethods: ['Google OAuth', 'Service account'],
    requiredFields: ['Sheet URL', 'Tab or range'],
    examples: ['Planning sheet', 'Supplier scorecard'],
  },
  {
    key: 'onedrive',
    name: 'OneDrive',
    category: 'Cloud',
    kind: 'cloud',
    description: 'OneDrive files and folder-based recurring imports.',
    authMethods: ['Microsoft OAuth'],
    requiredFields: ['File or folder URL'],
    examples: ['Finance export', 'Daily CSV folder'],
  },
  {
    key: 'google_drive',
    name: 'Google Drive',
    category: 'Cloud',
    kind: 'cloud',
    description: 'Google Drive files, folders, and exported Google Sheets.',
    authMethods: ['Google OAuth', 'Service account'],
    requiredFields: ['Drive URL', 'File type'],
    examples: ['Shared folder', 'Supplier docs'],
  },
  {
    key: 'salesforce',
    name: 'Salesforce',
    category: 'Cloud',
    kind: 'cloud',
    description: 'CRM accounts, opportunities, orders, cases, and custom objects.',
    authMethods: ['OAuth'],
    requiredFields: ['Instance URL', 'Object'],
    examples: ['Accounts', 'Orders', 'Cases'],
  },
  {
    key: 'zoho',
    name: 'Zoho',
    category: 'Cloud',
    kind: 'cloud',
    description: 'Zoho CRM, Inventory, Books, and custom module data.',
    authMethods: ['OAuth'],
    requiredFields: ['App', 'Module'],
    examples: ['Zoho Inventory', 'Zoho Books'],
  },
  {
    key: 'servicenow',
    name: 'ServiceNow',
    category: 'Cloud',
    kind: 'cloud',
    description: 'Tickets, assets, workflow records, and service history.',
    authMethods: ['OAuth', 'Basic authentication'],
    requiredFields: ['Instance URL', 'Table'],
    examples: ['incidents', 'assets', 'change requests'],
  },
  {
    key: 'rest_api',
    name: 'REST API',
    category: 'Cloud',
    kind: 'api',
    description: 'JSON or XML endpoints with headers, parameters, pagination, and retry policy.',
    authMethods: ['API key', 'Bearer token', 'OAuth', 'Basic authentication'],
    requiredFields: ['Base URL', 'Endpoint', 'Authentication'],
    examples: ['/inventory', '/orders', '/events'],
  },
  {
    key: 'graphql',
    name: 'GraphQL API',
    category: 'Cloud',
    kind: 'api',
    description: 'GraphQL queries, variables, endpoint authentication, and response flattening.',
    authMethods: ['Bearer token', 'OAuth'],
    requiredFields: ['Endpoint', 'Query'],
    examples: ['Orders query', 'Inventory query'],
  },
  {
    key: 'web_url',
    name: 'Web URL',
    category: 'Cloud',
    kind: 'api',
    description: 'Public or internal web tables, HTML tables, and simple downloadable URLs.',
    authMethods: ['No authentication', 'Header authentication'],
    requiredFields: ['URL'],
    examples: ['Published table', 'CSV endpoint'],
  },
  {
    key: 'odata',
    name: 'OData feed',
    category: 'Cloud',
    kind: 'api',
    description: 'OData entities from SAP, Dynamics, and service feeds.',
    authMethods: ['OAuth', 'Basic authentication', 'API key'],
    requiredFields: ['Service root', 'Entity set'],
    examples: ['SAP OData', 'Dynamics feed'],
  },
  {
    key: 'webhook',
    name: 'Webhook receiver',
    category: 'Cloud',
    kind: 'api',
    description: 'Real-time inbound updates for events, scans, machines, and business records.',
    authMethods: ['Signed secret', 'Bearer token'],
    requiredFields: ['Webhook name', 'Signature secret'],
    examples: ['Barcode scan', 'Machine alarm'],
  },
  {
    key: 'erp',
    name: 'ERP',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'Master data, inventory, finance, purchasing, production, and order records.',
    authMethods: ['API key', 'OAuth', 'Database read-only', 'SFTP export'],
    requiredFields: ['System URL', 'Company code', 'Object'],
    examples: ['SAP S/4HANA', 'Oracle EBS', 'Dynamics'],
  },
  {
    key: 'mes',
    name: 'MES',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'Production execution, work orders, line status, OEE, downtime, and WIP.',
    authMethods: ['API token', 'Database read-only', 'OPC bridge'],
    requiredFields: ['Endpoint', 'Line/work center'],
    examples: ['Work orders', 'OEE events'],
  },
  {
    key: 'wms',
    name: 'WMS',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'Receiving, putaway, bins, picking, packing, dispatch, and occupancy data.',
    authMethods: ['API token', 'Database read-only', 'File export'],
    requiredFields: ['Endpoint', 'Warehouse'],
    examples: ['Bin balance', 'Pick tasks'],
  },
  {
    key: 'scm',
    name: 'SCM',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'Supply planning, supplier lead time, shipment, logistics, and demand signals.',
    authMethods: ['API key', 'EDI credentials', 'File export'],
    requiredFields: ['System URL', 'Data object'],
    examples: ['Shipments', 'Supplier commits'],
  },
  {
    key: 'iot_machine',
    name: 'IoT machine data',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'Machine telemetry, runtime, temperature, throughput, and condition data.',
    authMethods: ['MQTT certificate', 'Bearer token'],
    requiredFields: ['Broker/endpoint', 'Topic or stream'],
    examples: ['MQTT topic', 'Time-series stream'],
  },
  {
    key: 'plc_device',
    name: 'PLC / device data',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'PLC values through OPC-UA, gateway, edge bridge, or device historian.',
    authMethods: ['Certificate', 'Gateway token'],
    requiredFields: ['OPC endpoint', 'Node path'],
    examples: ['OPC-UA', 'Edge gateway'],
  },
  {
    key: 'barcode_rfid',
    name: 'Barcode / RFID',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'Scan events for item, pallet, bin, receipt, transfer, and dispatch movements.',
    authMethods: ['Device key', 'Webhook secret', 'File feed'],
    requiredFields: ['Event stream', 'Device group'],
    examples: ['Scan events', 'Pallet moves'],
  },
  {
    key: 'sensor_data',
    name: 'Sensor data',
    category: 'Manufacturing',
    kind: 'manufacturing',
    description: 'Environmental, safety, quality, and condition monitoring sensor values.',
    authMethods: ['Token', 'Certificate'],
    requiredFields: ['Endpoint', 'Sensor group'],
    examples: ['Temperature', 'Humidity', 'Vibration'],
  },
  {
    key: 'manual_entry',
    name: 'Manual entry',
    category: 'Manual',
    kind: 'manual',
    description: 'Controlled manual rows for small corrections, master data, and demo records.',
    authMethods: ['Platform permissions'],
    requiredFields: ['Table name', 'Destination module'],
    examples: ['Manual item', 'Supplier correction'],
  },
  {
    key: 'bulk_paste',
    name: 'Bulk copy-paste',
    category: 'Manual',
    kind: 'manual',
    description: 'Paste tabular rows from spreadsheets and validate before creating an import draft.',
    authMethods: ['Platform permissions'],
    requiredFields: ['Pasted rows', 'Header row'],
    examples: ['Copied Excel rows', 'Ad-hoc table'],
  },
  {
    key: 'template_upload',
    name: 'Template upload',
    category: 'Manual',
    kind: 'manual',
    description: 'Download a platform template, fill it, then upload and validate.',
    authMethods: ['Platform permissions'],
    requiredFields: ['Template', 'Completed file'],
    examples: ['Inventory template', 'User template'],
  },
];

export const connectorCategories = ['Files', 'Databases', 'Cloud', 'Manufacturing', 'Manual'] as const;

export const destinationModules = [
  'Inventory',
  'Planning',
  'Production',
  'Warehouse',
  'Maintenance',
  'Quality',
  'Procurement',
  'Sales & Distribution',
  'Costing & Profitability',
  'Reports & Analytics',
  'Admin master data',
];

export const refreshModes = [
  'One-time import',
  'Manual refresh',
  'Scheduled refresh',
  'Incremental refresh',
  'Real-time webhook update',
  'Retry failed refresh',
];

export const transformOperations = [
  'Rename columns',
  'Remove columns',
  'Change data type',
  'Filter rows',
  'Sort rows',
  'Replace values',
  'Split columns',
  'Merge columns',
  'Trim text',
  'Format dates',
  'Format currency',
  'Remove duplicates',
  'Group by',
  'Calculated column',
];

export function connectorByKey(key: string) {
  return dataHubConnectors.find((connector) => connector.key === key) ?? dataHubConnectors[0];
}
