import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const outputDir = path.resolve('app', 'import_templates', 'super_admin');

const commonColumns = [
  'tenant_id',
  'client_id',
  'client_code',
  'client_name',
  'plant_id',
  'plant_code',
  'plant_name',
  'warehouse_id',
  'warehouse_code',
  'warehouse_name',
  'module_key',
  'source_system',
  'source_record_id',
  'source_last_updated',
  'record_status',
  'data_classification',
  'audit_reason',
];

const definitions = [
  {
    file: '01_platform_clients.csv',
    module: 'Platform Admin',
    category: 'Master Data',
    description: 'Client master data used to create companies and tenant context.',
    columns: [
      'tenant_id',
      'client_id',
      'client_code',
      'client_name',
      'legal_name',
      'industry',
      'region',
      'market',
      'currency',
      'status',
      'tax_registration_id',
      'primary_admin_email',
      'support_tier',
      'subscription_plan',
      'subscription_start_date',
      'subscription_end_date',
      'created_reason',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC-MANUFACTURING', 'ABC Manufacturing', 'ABC Manufacturing Pvt Ltd', 'Manufacturing', 'North America', 'United States', 'USD', 'Active', 'US-TAX-10001', 'admin.abc@metam.local', 'Enterprise', 'Premium Operations', '2026-01-01', '2026-12-31', 'Initial migration'],
    ],
  },
  {
    file: '02_platform_plants.csv',
    module: 'Platform Admin',
    category: 'Master Data',
    description: 'Plant master data linked to client records and operational modules.',
    columns: [
      'tenant_id',
      'client_id',
      'client_code',
      'plant_id',
      'plant_code',
      'plant_name',
      'plant_type',
      'region',
      'market',
      'timezone',
      'address_line_1',
      'city',
      'state',
      'postal_code',
      'status',
      'plant_manager_email',
      'created_reason',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC-MANUFACTURING', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'Manufacturing', 'North America', 'United States', 'America/New_York', '100 Industrial Way', 'Dallas', 'TX', '75001', 'Active', 'plant.manager.abcmanufacturing@metam.local', 'Default test plant'],
    ],
  },
  {
    file: '03_platform_users.csv',
    module: 'Platform Admin',
    category: 'User Access',
    description: 'User import template with role, application, module, and plant scope.',
    columns: [
      'tenant_id',
      'client_id',
      'client_code',
      'plant_id',
      'user_id',
      'first_name',
      'last_name',
      'display_name',
      'email',
      'login_name',
      'role_keys',
      'assigned_application_keys',
      'assigned_module_keys',
      'department',
      'manager_email',
      'scope_plant_id',
      'scope_warehouse_id',
      'status',
      'force_password_change',
      'password_expires_every_days',
      'created_reason',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC-MANUFACTURING', 'ABC-PLT-001', 'USR-ABC-0001', 'Noah', 'Warehouse', 'Noah Warehouse', 'warehouse.lead.abcmanufacturing@metam.local', 'noah.warehouse', 'warehouse_manager', 'operations', 'inventory|warehouse|reports', 'Warehouse', 'plant.manager.abcmanufacturing@metam.local', 'ABC-PLT-001', 'ABC-WH-001', 'Active', 'true', '90', 'Warehouse scope test user'],
    ],
  },
  {
    file: '04_module_entitlements.csv',
    module: 'Platform Admin',
    category: 'Access Control',
    description: 'Company-level module enablement, independent from user data visibility.',
    columns: [
      'tenant_id',
      'client_id',
      'client_code',
      'application_key',
      'module_key',
      'module_display_name',
      'enabled',
      'valid_from',
      'valid_until',
      'reason',
      'approved_by_email',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC-MANUFACTURING', 'operations', 'inventory', 'Inventory', 'true', '2026-01-01', '', 'Enabled for ABC test client', 'super@metam.local'],
    ],
  },
  {
    file: '05_planning.csv',
    module: 'Planning',
    category: 'Operations',
    description: 'Demand, supply, capacity, workforce, and material planning records.',
    columns: [
      ...commonColumns,
      'planning_record_id',
      'plan_type',
      'demand_plan_id',
      'forecast_version',
      'product_id',
      'product_code',
      'product_name',
      'customer_id',
      'sales_order_id',
      'period_start',
      'period_end',
      'forecast_quantity',
      'planned_quantity',
      'capacity_hours_required',
      'workforce_hours_required',
      'planner_email',
      'approval_status',
      'related_inventory_item_id',
      'related_production_order_id',
      'exception_code',
      'exception_message',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'planning', 'ERP', 'ERP-PLAN-001', '2026-08-01T09:00:00Z', 'Open', 'internal', 'Initial plan load', 'PLAN-0001', 'Demand Plan', 'DEM-2026-08', 'V1', 'PRD-001', 'PUMP-ASM-100', 'Pump Assembly', 'CUST-001', 'SO-10001', '2026-08-01', '2026-08-31', '26500', '12500', '720', '540', 'planning.manager.abcmanufacturing@metam.local', 'Draft', 'INV-0001', 'PO-0001', 'SHORTAGE', 'Material shortage for steel coil'],
    ],
  },
  {
    file: '06_inventory.csv',
    module: 'Inventory',
    category: 'Operations',
    description: 'Stock, batch, serial, reservation, valuation, and location records.',
    columns: [
      ...commonColumns,
      'inventory_item_id',
      'item_code',
      'item_name',
      'item_category',
      'item_type',
      'uom',
      'batch_id',
      'serial_number',
      'supplier_id',
      'supplier_batch',
      'manufacturing_date',
      'expiry_date',
      'stock_status',
      'quantity_on_hand',
      'available_quantity',
      'reserved_quantity',
      'allocated_quantity',
      'in_transit_quantity',
      'quarantine_quantity',
      'rejected_quantity',
      'damaged_quantity',
      'reorder_level',
      'safety_stock',
      'unit_cost',
      'inventory_value',
      'bin_id',
      'related_purchase_order_id',
      'related_production_order_id',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'inventory', 'WMS', 'WMS-INV-001', '2026-08-01T09:05:00Z', 'Available', 'internal', 'Opening balance', 'INV-0001', 'RM-STEEL-001', 'Steel Coil', 'Raw Material', 'batch', 'KG', 'BATCH-STEEL-202608', '', 'SUP-001', 'SUP-B-8842', '2026-07-10', '2027-07-10', 'Available', '680', '520', '100', '60', '0', '0', '0', '0', '120', '200', '42.50', '28900', 'BIN-A-01-001', 'PO-550001', 'PROD-0001'],
    ],
  },
  {
    file: '07_warehouse.csv',
    module: 'Warehouse',
    category: 'Operations',
    description: 'Warehouse location, occupancy, movement, task, and scanning data.',
    columns: [
      ...commonColumns,
      'warehouse_record_id',
      'zone_id',
      'rack_id',
      'shelf_id',
      'bin_id',
      'bin_barcode',
      'location_type',
      'capacity_uom',
      'capacity_total',
      'capacity_used',
      'occupancy_percent',
      'item_code',
      'batch_id',
      'handling_unit_id',
      'movement_type',
      'from_bin_id',
      'to_bin_id',
      'task_id',
      'task_status',
      'operator_email',
      'equipment_id',
      'scan_timestamp',
      'related_inventory_item_id',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'warehouse', 'WMS', 'WMS-WH-001', '2026-08-01T09:06:00Z', 'Open', 'internal', 'Bin occupancy import', 'WHREC-0001', 'ZONE-A', 'RACK-01', 'SHELF-01', 'BIN-A-01-001', 'ABC-A01001', 'Storage', 'PALLET', '100', '77', '77', 'RM-STEEL-001', 'BATCH-STEEL-202608', 'HU-0001', 'Putaway', 'DOCK-01', 'BIN-A-01-001', 'TASK-0001', 'Open', 'warehouse.operator.abcmanufacturing@metam.local', 'FORK-01', '2026-08-01T09:10:00Z', 'INV-0001'],
    ],
  },
  {
    file: '08_production.csv',
    module: 'Production',
    category: 'Operations',
    description: 'Production orders, work centers, WIP, output, scrap, and line status.',
    columns: [
      ...commonColumns,
      'production_order_id',
      'work_order_id',
      'bom_id',
      'routing_id',
      'product_code',
      'product_name',
      'line_id',
      'work_center_id',
      'shift_id',
      'planned_start',
      'planned_end',
      'actual_start',
      'actual_end',
      'order_quantity',
      'completed_quantity',
      'scrap_quantity',
      'wip_quantity',
      'status',
      'priority',
      'required_material_item_ids',
      'consumed_material_item_ids',
      'related_planning_record_id',
      'related_quality_lot_id',
      'supervisor_email',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'production', 'MES', 'MES-PROD-001', '2026-08-01T09:12:00Z', 'Released', 'internal', 'Production order import', 'PROD-0001', 'WO-0001', 'BOM-PUMP-100', 'ROUTE-PUMP-100', 'PUMP-ASM-100', 'Pump Assembly', 'LINE-01', 'WC-ASSY-01', 'SHIFT-A', '2026-08-01T08:00:00Z', '2026-08-01T16:00:00Z', '2026-08-01T08:05:00Z', '', '500', '225', '4', '271', 'In Progress', 'High', 'INV-0001|INV-0002', 'INV-0001', 'PLAN-0001', 'QL-0001', 'production.supervisor.abcmanufacturing@metam.local'],
    ],
  },
  {
    file: '09_maintenance.csv',
    module: 'Maintenance',
    category: 'Operations',
    description: 'Asset reliability, work orders, downtime, spares, and maintenance cost.',
    columns: [
      ...commonColumns,
      'asset_id',
      'asset_code',
      'asset_name',
      'asset_type',
      'maintenance_order_id',
      'work_request_id',
      'maintenance_type',
      'priority',
      'failure_code',
      'failure_description',
      'planned_start',
      'planned_end',
      'actual_start',
      'actual_end',
      'downtime_minutes',
      'technician_email',
      'spare_part_item_code',
      'spare_part_quantity',
      'work_status',
      'pm_schedule_id',
      'related_production_order_id',
      'safety_permit_id',
      'cost_amount',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'maintenance', 'CMMS', 'CMMS-MNT-001', '2026-08-01T09:20:00Z', 'Open', 'internal', 'Corrective work order import', 'AST-0001', 'MIXER-01', 'Mixer 01', 'Mixer', 'MNT-0001', 'WR-0001', 'Corrective', 'High', 'BRG-FAIL', 'Bearing vibration above threshold', '2026-08-01T10:00:00Z', '2026-08-01T12:00:00Z', '', '', '0', 'maintenance.tech.abcmanufacturing@metam.local', 'SP-BEAR-009', '2', 'Open', 'PM-MIXER-01', 'PROD-0001', 'PERMIT-0001', '1250'],
    ],
  },
  {
    file: '10_quality.csv',
    module: 'Quality',
    category: 'Operations',
    description: 'Inspection, defects, quarantine, rejection, CAPA, and supplier quality data.',
    columns: [
      ...commonColumns,
      'quality_lot_id',
      'inspection_plan_id',
      'inspection_type',
      'product_code',
      'batch_id',
      'sample_size',
      'inspected_quantity',
      'accepted_quantity',
      'rejected_quantity',
      'defect_code',
      'defect_description',
      'severity',
      'disposition',
      'quarantine_location_id',
      'inspector_email',
      'inspection_date',
      'capa_id',
      'related_production_order_id',
      'related_supplier_id',
      'related_inventory_item_id',
      'approval_status',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'quality', 'QMS', 'QMS-QL-001', '2026-08-01T09:25:00Z', 'Pending', 'internal', 'Incoming inspection', 'QL-0001', 'IP-PUMP-100', 'In Process', 'PUMP-ASM-100', 'BATCH-PUMP-202608', '50', '50', '48', '2', 'SURFACE-SCRATCH', 'Surface scratch on housing', 'Medium', 'Rework', 'QUAR-BIN-001', 'quality.inspector.abcmanufacturing@metam.local', '2026-08-01', 'CAPA-0001', 'PROD-0001', 'SUP-001', 'INV-0001', 'Pending'],
    ],
  },
  {
    file: '11_procurement.csv',
    module: 'Procurement',
    category: 'Operations',
    description: 'Purchase requests, orders, supplier lead times, receipts, and approvals.',
    columns: [
      ...commonColumns,
      'purchase_request_id',
      'purchase_order_id',
      'supplier_id',
      'supplier_code',
      'supplier_name',
      'item_code',
      'item_description',
      'requested_quantity',
      'ordered_quantity',
      'received_quantity',
      'uom',
      'required_date',
      'promised_date',
      'supplier_lead_time_days',
      'price_per_unit',
      'currency',
      'po_status',
      'approval_status',
      'related_inventory_item_id',
      'related_warehouse_receipt_id',
      'requester_email',
      'buyer_email',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'procurement', 'ERP', 'ERP-PO-001', '2026-08-01T09:30:00Z', 'Open', 'confidential', 'Purchase order import', 'PR-0001', 'PO-550001', 'SUP-001', 'SUP-STEEL', 'Steel Supplier Inc', 'RM-STEEL-001', 'Steel Coil', '1000', '1000', '0', 'KG', '2026-08-05', '2026-08-07', '7', '41.80', 'USD', 'Released', 'Approved', 'INV-0001', 'GR-0001', 'planning.manager.abcmanufacturing@metam.local', 'buyer.abcmanufacturing@metam.local'],
    ],
  },
  {
    file: '12_sales.csv',
    module: 'Sales & Distribution',
    category: 'Commercial',
    description: 'Customer orders, fulfillment, shipment, invoicing, and demand links.',
    columns: [
      ...commonColumns,
      'customer_id',
      'customer_code',
      'customer_name',
      'sales_order_id',
      'order_line_id',
      'product_code',
      'ordered_quantity',
      'confirmed_quantity',
      'shipped_quantity',
      'order_date',
      'requested_ship_date',
      'promised_ship_date',
      'order_status',
      'fulfillment_status',
      'ship_to_region',
      'ship_to_market',
      'related_inventory_reservation_id',
      'related_production_order_id',
      'invoice_id',
      'revenue_amount',
      'currency',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'sales', 'CRM', 'CRM-SO-001', '2026-08-01T09:35:00Z', 'Open', 'confidential', 'Sales order import', 'CUST-001', 'CUST-NOVA', 'Nova Customer', 'SO-10001', 'SO-10001-10', 'PUMP-ASM-100', '500', '480', '0', '2026-08-01', '2026-08-15', '2026-08-16', 'Confirmed', 'Awaiting Production', 'North America', 'United States', 'RES-0001', 'PROD-0001', 'INV-90001', '124000', 'USD'],
    ],
  },
  {
    file: '13_costing.csv',
    module: 'Costing & Profitability',
    category: 'Finance',
    description: 'Cost object, variance, valuation, profitability, and financial impact data.',
    columns: [
      ...commonColumns,
      'cost_record_id',
      'cost_object_type',
      'cost_object_id',
      'product_code',
      'cost_center_id',
      'gl_account',
      'cost_type',
      'material_cost',
      'labor_cost',
      'overhead_cost',
      'maintenance_cost',
      'quality_cost',
      'logistics_cost',
      'total_cost',
      'currency',
      'period_start',
      'period_end',
      'variance_amount',
      'variance_reason',
      'related_production_order_id',
      'related_inventory_item_id',
      'finance_owner_email',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'costing', 'ERP Finance', 'ERP-COST-001', '2026-08-01T09:40:00Z', 'Posted', 'restricted', 'Costing import', 'COST-0001', 'Production Order', 'PROD-0001', 'PUMP-ASM-100', 'CC-ASSY-01', '500100', 'Actual', '52500', '14200', '8300', '1250', '900', '2400', '79550', 'USD', '2026-08-01', '2026-08-31', '3200', 'Material price variance', 'PROD-0001', 'INV-0001', 'finance.controller.abcmanufacturing@metam.local'],
    ],
  },
  {
    file: '14_compliance.csv',
    module: 'Compliance',
    category: 'Governance',
    description: 'Controls, findings, evidence, audit trail, and corrective action data.',
    columns: [
      ...commonColumns,
      'compliance_record_id',
      'regulation_code',
      'regulation_name',
      'compliance_domain',
      'requirement_id',
      'control_id',
      'evidence_document_id',
      'evidence_status',
      'audit_period',
      'audit_date',
      'responsible_owner_email',
      'risk_rating',
      'finding_status',
      'corrective_action_id',
      'due_date',
      'closure_date',
      'related_quality_lot_id',
      'related_supplier_id',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'compliance', 'GRC', 'GRC-COMP-001', '2026-08-01T09:45:00Z', 'Open', 'confidential', 'Audit evidence import', 'COMP-0001', 'ISO-9001', 'ISO 9001 Quality Management', 'Quality', 'REQ-8.5.1', 'CTRL-QA-001', 'DOC-0001', 'Submitted', '2026-Q3', '2026-08-01', 'quality.manager.abcmanufacturing@metam.local', 'Medium', 'Open', 'CA-0001', '2026-08-20', '', 'QL-0001', 'SUP-001'],
    ],
  },
  {
    file: '15_customer_portal.csv',
    module: 'Customer Portal',
    category: 'Portal',
    description: 'Customer requests, order questions, shipment issues, and support records.',
    columns: [
      ...commonColumns,
      'portal_record_id',
      'customer_id',
      'customer_name',
      'request_type',
      'request_id',
      'related_sales_order_id',
      'related_shipment_id',
      'product_code',
      'issue_category',
      'priority',
      'status',
      'created_by_email',
      'assigned_to_email',
      'created_at',
      'due_at',
      'resolution_summary',
      'satisfaction_score',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'customer-portal', 'CRM Portal', 'PORT-CUST-001', '2026-08-01T09:50:00Z', 'Open', 'internal', 'Customer portal request import', 'CP-0001', 'CUST-001', 'Nova Customer', 'Order Status', 'REQ-CUST-0001', 'SO-10001', 'SHIP-0001', 'PUMP-ASM-100', 'Delivery Date', 'Medium', 'Open', 'customer.user@example.com', 'sales.manager.abcmanufacturing@metam.local', '2026-08-01T09:50:00Z', '2026-08-03T17:00:00Z', '', ''],
    ],
  },
  {
    file: '16_supplier_portal.csv',
    module: 'Supplier Portal',
    category: 'Portal',
    description: 'Supplier collaboration, purchase order updates, ASN, and supplier quality issues.',
    columns: [
      ...commonColumns,
      'portal_record_id',
      'supplier_id',
      'supplier_name',
      'request_type',
      'request_id',
      'related_purchase_order_id',
      'related_quality_lot_id',
      'item_code',
      'issue_category',
      'priority',
      'status',
      'supplier_contact_email',
      'buyer_email',
      'created_at',
      'due_at',
      'resolution_summary',
      'supplier_rating',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'supplier-portal', 'Supplier Portal', 'PORT-SUP-001', '2026-08-01T09:55:00Z', 'Open', 'internal', 'Supplier collaboration import', 'SP-0001', 'SUP-001', 'Steel Supplier Inc', 'PO Confirmation', 'REQ-SUP-0001', 'PO-550001', 'QL-0001', 'RM-STEEL-001', 'Delivery Confirmation', 'High', 'Open', 'supplier.contact@example.com', 'buyer.abcmanufacturing@metam.local', '2026-08-01T09:55:00Z', '2026-08-02T17:00:00Z', '', '4.5'],
    ],
  },
  {
    file: '17_reports_analytics.csv',
    module: 'Reports & Analytics',
    category: 'Analytics',
    description: 'Report, dashboard, KPI, dataset, refresh, and export metadata.',
    columns: [
      ...commonColumns,
      'report_id',
      'report_name',
      'report_domain',
      'dataset_id',
      'data_source_id',
      'refresh_mode',
      'refresh_status',
      'last_refresh_at',
      'row_count',
      'owner_email',
      'visibility_level',
      'export_allowed',
      'related_dashboard_id',
      'kpi_name',
      'kpi_value',
      'kpi_period',
      'quality_score',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'reports', 'BI', 'BI-REP-001', '2026-08-01T10:00:00Z', 'Active', 'internal', 'Report catalog import', 'RPT-0001', 'Inventory Health', 'Inventory', 'DS-INV-001', 'CONN-WMS-001', 'Scheduled refresh', 'Completed', '2026-08-01T10:00:00Z', '12480', 'analytics.owner.abcmanufacturing@metam.local', 'Managers', 'true', 'DASH-INV-001', 'Inventory Accuracy', '98.1', '2026-08', '93'],
    ],
  },
  {
    file: '18_document_management.csv',
    module: 'Document Management',
    category: 'Documents',
    description: 'Controlled documents linked to modules, entities, approvals, and retention rules.',
    columns: [
      ...commonColumns,
      'document_id',
      'document_type',
      'document_title',
      'file_name',
      'file_url',
      'version',
      'entity_type',
      'entity_id',
      'owner_email',
      'approval_status',
      'effective_date',
      'expiry_date',
      'classification',
      'retention_policy',
      'related_audit_id',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'documents', 'DMS', 'DMS-DOC-001', '2026-08-01T10:05:00Z', 'Approved', 'confidential', 'Controlled document import', 'DOC-0001', 'Work Instruction', 'Pump Assembly Work Instruction', 'WI-PUMP-100.pdf', 'https://docs.example.local/WI-PUMP-100.pdf', '1.0', 'production_order', 'PROD-0001', 'document.controller.abcmanufacturing@metam.local', 'Approved', '2026-08-01', '2027-08-01', 'Internal', '7 years', 'AUD-0001'],
    ],
  },
  {
    file: '19_manufacturing_data_hub.csv',
    module: 'Manufacturing Data Hub',
    category: 'Data Hub',
    description: 'Connector, catalog, field mapping, transform, quality, and AI readiness metadata.',
    columns: [
      ...commonColumns,
      'catalog_entry_id',
      'data_type',
      'connector_key',
      'connector_category',
      'connection_id',
      'data_owner_email',
      'dataset_name',
      'table_name',
      'source_field_name',
      'target_entity',
      'target_field',
      'transform_rule',
      'quality_score',
      'ai_ready',
      'refresh_mode',
      'last_sync_at',
      'related_module_key',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'manufacturing-data-hub', 'Data Hub', 'DH-CAT-001', '2026-08-01T10:10:00Z', 'Active', 'internal', 'Catalog import', 'CAT-0001', 'Inventory', 'excel', 'Files', 'CONN-0001', 'data.owner.abcmanufacturing@metam.local', 'WMS Stock Balance', 'stock_balance', 'item_code', 'InventoryRecord', 'item_code', 'trim|uppercase', '95', 'true', 'Scheduled refresh', '2026-08-01T10:10:00Z', 'inventory'],
    ],
  },
  {
    file: '20_integration_hub.csv',
    module: 'Integration Hub',
    category: 'Integration',
    description: 'System-to-system connector status, schedules, sync direction, errors, and ownership.',
    columns: [
      ...commonColumns,
      'integration_id',
      'integration_name',
      'source_system',
      'target_system',
      'source_module_key',
      'target_module_key',
      'connector_type',
      'auth_method',
      'endpoint_url',
      'schedule',
      'sync_direction',
      'last_sync_at',
      'sync_status',
      'records_processed',
      'records_failed',
      'error_code',
      'error_message',
      'retry_count',
      'owner_email',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'integration-hub', 'Integration Runtime', 'INT-001', '2026-08-01T10:15:00Z', 'Healthy', 'confidential', 'Integration import', 'INT-0001', 'WMS to Inventory Sync', 'WMS', 'Metam Services', 'warehouse', 'inventory', 'REST API', 'OAuth2', 'https://api.wms.example.local/stock', 'Every 15 minutes', 'Inbound', '2026-08-01T10:15:00Z', 'Completed', '12480', '0', '', '', '0', 'integration.owner.abcmanufacturing@metam.local'],
    ],
  },
  {
    file: '21_ai_intelligence.csv',
    module: 'AI Intelligence',
    category: 'Intelligence',
    description: 'AI signal, prediction, risk, recommendation, and human approval metadata.',
    columns: [
      ...commonColumns,
      'ai_signal_id',
      'ai_domain',
      'model_name',
      'model_version',
      'input_dataset_id',
      'target_module_key',
      'entity_type',
      'entity_id',
      'prediction_type',
      'prediction_value',
      'confidence_score',
      'risk_level',
      'recommendation_text',
      'recommended_action',
      'human_approval_required',
      'generated_at',
      'reviewed_by_email',
      'decision_status',
    ],
    rows: [
      ['tenant-demo-001', 'CLT-000001', 'ABC', 'ABC Manufacturing', 'ABC-PLT-001', 'PLANT-A', 'Plant A', 'ABC-WH-001', 'WH-A', 'Main Warehouse', 'ai-intelligence', 'AI Engine', 'AI-SIG-001', '2026-08-01T10:20:00Z', 'Draft', 'confidential', 'AI recommendation import', 'AI-0001', 'Inventory Risk', 'InventoryRiskRules', '1.0.0', 'DS-INV-001', 'inventory', 'inventory_item', 'INV-0001', 'Stockout Risk', 'High in 7 days', '0.87', 'High', 'Create purchase request draft for steel coil', 'draft_reorder', 'true', '2026-08-01T10:20:00Z', '', 'Pending Review'],
    ],
  },
];

const dataTypeFor = (column) => {
  if (column.endsWith('_date')) return 'date';
  if (column.endsWith('_at') || column.includes('timestamp') || column === 'source_last_updated') return 'datetime';
  if (column.includes('quantity') || column.includes('cost') || column.includes('value') || column.includes('score') || column.includes('percent') || column.includes('amount') || column.includes('price') || column.includes('count') || column.includes('hours') || column.includes('days') || column.includes('minutes')) return 'number';
  if (column.startsWith('is_') || column.endsWith('_allowed') || column === 'enabled' || column === 'ai_ready' || column === 'force_password_change' || column === 'human_approval_required') return 'boolean';
  return 'text';
};

const requiredColumns = new Set([
  'tenant_id',
  'client_id',
  'client_code',
  'client_name',
  'plant_id',
  'plant_code',
  'plant_name',
  'module_key',
  'source_system',
  'source_record_id',
  'record_status',
]);

function csvEscape(value) {
  const text = String(value ?? '');
  if (/[",\n\r]/.test(text)) return `"${text.replaceAll('"', '""')}"`;
  return text;
}

function toCsv(rows) {
  return rows.map((row) => row.map(csvEscape).join(',')).join('\n') + '\n';
}

function columnPurpose(column) {
  if (column.endsWith('_id') || column === 'tenant_id') return 'System/linking identifier used for database alignment.';
  if (column.includes('related_')) return 'Cross-module relationship key.';
  if (column === 'module_key') return 'Destination module key used by Data Hub routing.';
  if (column === 'data_classification') return 'Security classification used for access control.';
  if (column === 'audit_reason') return 'Reason captured for audit trail before import.';
  if (column.includes('status')) return 'Workflow/status field used for filters and dashboards.';
  return 'Business data field for module import and mapping.';
}

async function main() {
  await mkdir(outputDir, { recursive: true });

  const manifestRows = [
    ['file_name', 'module', 'category', 'description', 'column_count', 'required_linking_columns'],
    ...definitions.map((definition) => [
      definition.file,
      definition.module,
      definition.category,
      definition.description,
      String(definition.columns.length),
      definition.columns.filter((column) => requiredColumns.has(column)).join('|'),
    ]),
  ];

  const dictionaryRows = [
    ['file_name', 'module', 'column_name', 'data_type', 'required', 'purpose'],
    ...definitions.flatMap((definition) =>
      definition.columns.map((column) => [
        definition.file,
        definition.module,
        column,
        dataTypeFor(column),
        requiredColumns.has(column) ? 'yes' : 'no',
        columnPurpose(column),
      ]),
    ),
  ];

  await writeFile(path.join(outputDir, '00_template_manifest.csv'), toCsv(manifestRows), 'utf8');
  await writeFile(path.join(outputDir, '00_field_dictionary.csv'), toCsv(dictionaryRows), 'utf8');

  for (const definition of definitions) {
    await writeFile(path.join(outputDir, definition.file), toCsv([definition.columns, ...definition.rows]), 'utf8');
  }

  console.log(`Created ${definitions.length + 2} Super Admin CSV template files in ${outputDir}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
